include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "test/mocks/**"
    - "**/*.g.dart"

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    use_key_in_widget_constructors: false
    always_specify_types: false
    no_logic_in_create_state: false
    use_build_context_synchronously: false # TODO: Re-enable when dart has the fix needed for this (https://github.com/dart-lang/linter/issues/4007)

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    prefer_single_quotes: true
    await_only_futures: true
    unawaited_futures: true
    require_trailing_commas: true
    always_use_package_imports: true
